# Week 6 Iris Assignment
## Francis Yang 11/8/2022

**Step 1:**
Load iris dataset from ScikitLearn using load_iris(). Assign the dataset to X and the target values to y. <br>
**Step 2:**
Print the dataset keys using `iris_dataset.keys()`


In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris

iris = load_iris()
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

**Step 3:**
Print the names of the categories in the target file


In [4]:
set(iris['target'])

{0, 1, 2}

**Step 4:**
Print the feature names in the Iris dataset


In [5]:
set(iris['feature_names'])

{'petal length (cm)',
 'petal width (cm)',
 'sepal length (cm)',
 'sepal width (cm)'}

**Step 5:**
Print the type of the Iris dataset.


In [6]:
type(iris)

sklearn.utils.Bunch

**Step 6:**
Print the shape of the Iris dataset.


In [11]:
iris['data'].shape

(150, 4)

**Step 7:**
Print the first five rows of the Iris dataset.


In [14]:
X = iris.data
X[0:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

**Step 8**
Print the type of the target variable of Iris dataset.


In [15]:
Y = iris.target
type(Y)

numpy.ndarray

**Step 9:**
Print the shape of the target variable of Iris dataset.


In [16]:
Y.shape

(150,)

**Step 10:**
Print the entire target variable values of the Iris dataset.


In [17]:
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

**Step 11:**
Import NumPy with `import numpy as np` and use the `np.unique()` function to print the unique values of the target variable of Iris dataset


In [19]:
np.unique(Y)

array([0, 1, 2])

**Step 12:**
Split dataset into train and test datasets using `from sklearn.model_selection import train_test_split`


In [21]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, stratify=Y)

**Step 13:**
Print the shape of train/test datasets and the train/test target variables.


In [22]:
print("X train",X_train.shape)
print("X test",X_test.shape)
print("y train",y_train.shape)
print("y test",y_test.shape)

X train (112, 4)
X test (38, 4)
y train (112,)
y test (38,)


**Step 14:**
Build your K-neighbors classifier for nearest neighbor of 1 using `from sklearn.neighbors import KNeighborsClassifier`, fit the model to your train dataset and make a prediction for the data point of [5, 1.9, 1, 0.2]. Print your prediction class value as an integer and also the corresponding string label.


In [29]:
from sklearn.neighbors import KNeighborsClassifier

predict = [5, 1.9, 1 ,0.2] # single data point with 4 features
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(X_train, y_train)

knn.predict([predict])

array([0])

In [24]:
knn.score(X_test, y_test)

0.9210526315789473