# Week 11 Module 7 Assignment 1
## Francis Yang 12/20/22
### Faces recognition example using eigenfaces and SVMs
Very similar to Module 4 Assignment 2

In [4]:
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.datasets import fetch_lfw_people
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.decomposition import PCA
from sklearn.svm import SVC
from sklearn.pipeline import Pipeline
import numpy as np

data = fetch_lfw_people(min_faces_per_person=70, resize=0.4)

pca = PCA(n_components=150, whiten=True, random_state=42)
svc = SVC(class_weight='balanced')

pipe = Pipeline([('pca',pca),('estimator',svc)])

X_train, X_test, y_train, y_test = train_test_split(
    data.data, data.target, random_state=2)

param_grid = {'estimator__C': np.arange(1, 15, 3),
              'estimator__gamma': np.linspace(0.0001, 0.01, num=15)}

grid = GridSearchCV(pipe, param_grid, cv=5)
grid.fit(X_train, y_train)

grid.best_params_

{'estimator__C': 4, 'estimator__gamma': 0.003635714285714286}

In [5]:
grid.best_score_

0.8623470968431175

In [7]:
model = grid.best_estimator_
yfit = model.predict(X_test)

print(classification_report(y_test, yfit,
                            target_names=data.target_names))

                   precision    recall  f1-score   support

     Ariel Sharon       0.93      0.68      0.79        19
     Colin Powell       0.73      0.78      0.75        55
  Donald Rumsfeld       0.71      0.68      0.69        25
    George W Bush       0.86      0.94      0.90       142
Gerhard Schroeder       0.93      0.87      0.90        31
      Hugo Chavez       1.00      0.75      0.86        16
       Tony Blair       0.83      0.71      0.76        34

         accuracy                           0.84       322
        macro avg       0.86      0.77      0.81       322
     weighted avg       0.84      0.84      0.84       322



In [8]:
print(confusion_matrix(y_test,yfit))

[[ 13   4   2   0   0   0   0]
 [  0  43   2   9   0   0   1]
 [  0   1  17   6   0   0   1]
 [  1   5   1 134   1   0   0]
 [  0   0   1   0  27   0   3]
 [  0   3   0   1   0  12   0]
 [  0   3   1   5   1   0  24]]
